package com.rest.jsonpath;

import java.util.List;

import com.jayway.jsonpath.ReadContext;

public class JsonPathThree {
	
	public static void main(String[] args) {
		String response = "{\r\n"
				+ "    \"properties\" : [\r\n"
				+ "    {\r\n"
				+ "        \"listing_id\": 1,\r\n"
				+ "        \"title\": \"Cozy Apartment in City Center\",\r\n"
				+ "        \"description\": \"Beautiful apartment with a view of the city skyline\",\r\n"
				+ "        \"price\": \"100.00\",\r\n"
				+ "        \"currency\": \"USD\",\r\n"
				+ "        \"city\": \"New York City\",\r\n"
				+ "        \"country\": \"USA\",\r\n"
				+ "        \"address\": \"123 Main St\",\r\n"
				+ "        \"latitude\": \"40.712800\",\r\n"
				+ "        \"longitude\": \"-74.006000\",\r\n"
				+ "        \"host_id\": 1,\r\n"
				+ "        \"created_at\": \"2024-08-02T18:51:54.000Z\",\r\n"
				+ "        \"updated_at\": \"2024-08-02T18:51:54.000Z\",\r\n"
				+ "        \"images\" : {\r\n"
				+ "            \"thumbnail\" : \"apartment.png\",\r\n"
				+ "            \"gallery\" : \"pool.jpg\",\r\n"
				+ "            \"source\" : {\r\n"
				+ "                \"validated\" : true,\r\n"
				+ "                \"isUploadedByUser\" : false\r\n"
				+ "            }\r\n"
				+ "        }\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"listing_id\": 2,\r\n"
				+ "        \"title\": \"Beach House with Ocean View\",\r\n"
				+ "        \"description\": \"Spacious beach house just steps away from the ocean\",\r\n"
				+ "        \"price\": \"150.00\",\r\n"
				+ "        \"currency\": \"USD\",\r\n"
				+ "        \"city\": \"Los Angeles\",\r\n"
				+ "        \"country\": \"USA\",\r\n"
				+ "        \"address\": \"456 Beach Blvd\",\r\n"
				+ "        \"latitude\": \"34.052200\",\r\n"
				+ "        \"longitude\": \"-118.243700\",\r\n"
				+ "        \"host_id\": 2,\r\n"
				+ "        \"created_at\": \"2024-08-02T18:51:54.000Z\",\r\n"
				+ "        \"updated_at\": \"2024-08-02T18:51:54.000Z\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"listing_id\": 3,\r\n"
				+ "        \"title\": \"Mountain Cabin Retreat\",\r\n"
				+ "        \"description\": \"Rustic cabin nestled in the mountains for a peaceful getaway\",\r\n"
				+ "        \"price\": \"120.00\",\r\n"
				+ "        \"currency\": \"USD\",\r\n"
				+ "        \"city\": \"Denver\",\r\n"
				+ "        \"country\": \"USA\",\r\n"
				+ "        \"address\": \"789 Mountain Rd\",\r\n"
				+ "        \"latitude\": \"39.739200\",\r\n"
				+ "        \"longitude\": \"-104.990300\",\r\n"
				+ "        \"host_id\": 3,\r\n"
				+ "        \"created_at\": \"2024-08-02T18:51:54.000Z\",\r\n"
				+ "        \"updated_at\": \"2024-08-02T18:51:54.000Z\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"listing_id\": 4,\r\n"
				+ "        \"title\": \"City Loft in Historic Building\",\r\n"
				+ "        \"description\": \"Chic loft apartment in a renovated historic building\",\r\n"
				+ "        \"price\": \"200.00\",\r\n"
				+ "        \"currency\": \"INR\",\r\n"
				+ "        \"city\": \"Chicago\",\r\n"
				+ "        \"country\": \"USA\",\r\n"
				+ "        \"address\": \"101 Loft Ave\",\r\n"
				+ "        \"latitude\": \"41.878100\",\r\n"
				+ "        \"longitude\": \"-87.629800\",\r\n"
				+ "        \"host_id\": 4,\r\n"
				+ "        \"created_at\": \"2024-08-02T18:51:54.000Z\",\r\n"
				+ "        \"updated_at\": \"2024-08-02T18:51:54.000Z\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"listing_id\": 5,\r\n"
				+ "        \"title\": \"Nice Hilltop stay in mulshi\",\r\n"
				+ "        \"description\": \"Enjoy cool breeze retreat in this fashionable party place with your doppelgangers\",\r\n"
				+ "        \"price\": \"12000.00\",\r\n"
				+ "        \"currency\": \"CHF\",\r\n"
				+ "        \"city\": \"Pune\",\r\n"
				+ "        \"country\": \"India\",\r\n"
				+ "        \"address\": \"Mulshi\",\r\n"
				+ "        \"latitude\": \"0.000000\",\r\n"
				+ "        \"longitude\": \"0.000000\",\r\n"
				+ "        \"host_id\": 7,\r\n"
				+ "        \"created_at\": \"2024-08-11T04:00:39.000Z\",\r\n"
				+ "        \"updated_at\": \"2024-08-11T04:00:39.000Z\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"listing_id\": 6,\r\n"
				+ "        \"title\": \"pune great maratha city\",\r\n"
				+ "        \"description\": \"dagdu seth temple is situated in pune city\",\r\n"
				+ "        \"price\": \"10000000.00\",\r\n"
				+ "        \"currency\": \"INR\",\r\n"
				+ "        \"city\": \"pune\",\r\n"
				+ "        \"country\": \"india\",\r\n"
				+ "        \"address\": \"near to shanivar wada dagduseth temple 411014\",\r\n"
				+ "        \"latitude\": \"91.878100\",\r\n"
				+ "        \"longitude\": \"-77.629800\",\r\n"
				+ "        \"host_id\": 6,\r\n"
				+ "        \"created_at\": \"2024-08-11T13:25:09.000Z\",\r\n"
				+ "        \"updated_at\": \"2024-08-11T13:30:35.000Z\"\r\n"
				+ "    },\r\n"
				+ "    {\r\n"
				+ "        \"listing_id\": 7,\r\n"
				+ "        \"title\": \"pune city in maratha history\",\r\n"
				+ "        \"description\": \"shanivar wada peshawa is renovated in pune city\",\r\n"
				+ "        \"price\": \"10000000.00\",\r\n"
				+ "        \"currency\": \"INR\",\r\n"
				+ "        \"city\": \"pune\",\r\n"
				+ "        \"country\": \"india\",\r\n"
				+ "        \"address\": \"shanivar wada pune 411014\",\r\n"
				+ "        \"latitude\": \"41.878100\",\r\n"
				+ "        \"longitude\": \"-87.629800\",\r\n"
				+ "        \"host_id\": 7,\r\n"
				+ "        \"created_at\": \"2024-08-11T13:37:43.000Z\",\r\n"
				+ "        \"updated_at\": \"2024-08-11T13:37:43.000Z\"\r\n"
				+ "    }\r\n"
				+ "]\r\n"
				+ "}";
		
		
		// Gson - Google Jsonpath - Already included in rest assured
		// JaywayJsonPath - externally include
		
//		JsonPath path = new JsonPath(response);
//		String attribute = path.getString("properties[0].images.source.validated"); // NOT THE RECOMMENDED WAY
//		System.out.println(attribute);
		
		ReadContext context = com.jayway.jsonpath.JsonPath.parse(response);
		List<String> prices = context.read("$.properties[?(@.listing_id < 6)]");
		System.out.println(prices);
	}
}
